### ISSUE TITLE
Texts for individual events 

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#1]
1. Georg Hajdu

![414_ansicht](https://user-images.githubusercontent.com/44872140/113860033-db534e80-97a5-11eb-970a-c7a7baa35402.jpg)

History: Three stages of Digital Art

While the groundwork for computer music and multimedia as we practice it today had been laid during the first part of the 20th century, the development of the digital computer during the middle of the previous century was a catalyst of gargantuan impact. Yet the beginnings of digital art were modest as artists had a vision but didn't really know how to teach a computer to accomplish what they were after. The post-war "tabula rasa" period in Europe and the United States was one of experimentation and speculation not just in digital art and much of what was produced was informed by the budding fields of information and communication theory. Yet in 1965 John R. Pierce expressed his frustration with the digital computer: 
"As a musical instrument, the computer has unlimited potentialities for uttering sound. It can, in fact, produce strings of numbers representing any conceivable or hearable sound... Wonderful things would come out of that box if only we knew how to evoke them." This chimed in a new phase in the exploration of the digital computer for art making. In the early 1970s, the first computer music centers were established as platforms for interdisciplinary research where composers, engineers, scholars and scientists were invited to collaborate. With personal computers being slow and costly, those centers remained major attractors for the technically minded composers and the artistically minded technologists, until the advent of broadband Internet and the development of cheap and extraordinarily efficient CPUs led to a paradigm shift around the turn of the millennium. The systematic exploration of the affordances of the computer gave way to a more intuitive and interactive manipulation of digital interfaces both for the acquisition of knowledge and the production of art. The postdigital era was born.

bio

Georg Hajdu grew up in Cologne where he obtained diplomas in molecular biology and musical composition from the University of Cologne and the Cologne University of Music and Dance. A stipend by the German Academic Exchange Service enabled him to enter the graduate program in composition at the University of California, Berkeley in 1990, working closely with the Center for New Music and Audio Technologies (CNMAT) and eventually obtaining a Ph.D. in 1994. 

In 1996, following residencies at IRCAM and the ZKM, Karlsruhe, he co-founded the ensemble WireWorks, a group specializing in the performance of electro-acoustic music. In 1999, he produced his full-length opera "Der Sprung – Beschreibung einer Oper" for which renowned author and filmmaker Thomas Brasch wrote the libretto. In May 2002, his Internet performance environment Quintet.net was employed in a Munich Biennale opera production (Orpheus Kristall by Manfred Stahnke), and in the same year Georg Hajdu became professor of multimedia composition at the Hamburg University of Music and Drama (HfMT). There, in 2004, he established Germany’s first master’s program in multimedia composition and, in 2012, the Center for Microtonal Music and Multimedia (ZM4). He was also involved in a number of large international projects such as CO-ME-DI-A, a European Culture 2007 project focussing on Networked Music Performance.

Hajdu has published compositions which are characterized by a pluralistic attitude and have earned him several international prizes, the IBM-prize of the Ensemble Modern among them. He is also the author of numerous articles on topics on the borderline of music, technology and science as well as software applications such MaxScore (with Nick Didkovsky), Quintet.net, DJster and a real-time version of Stockhausen’s Elektronische Studie II.

**Comment by fuxiao1208** [comment]
2. Alex

21.04.2021 18:30 UCT+2

title
Post-Digitality and Virtuality (as Compositional Practices)

event link: https://mutor-2.github.io/HistoryAndPracticeOfMultimedia/


foto
http://www.alexanderschubert.net/bilder/Alexander_Schubert_2019_A.jpg

bio  http://www.alexanderschubert.net/
Alexander Schubert (1979) studied bioinformatics, multimedia composition. He’s a professor at the Musikhochschule Hamburg.
Schubert’s interest explores the border between the acoustic and electronic world. In music composition, immersive installation and staged pieces he examines the interplay between the digital and the analogue. He creates pieces that realize test settings or interaction spaces that question modes of perception and representation. Continuing topics in this field are authenticity and virtuality. The influence and framing of digital media on aesthetic views and communication is researched in a post-digital perspective. Recent research topics in his works were virtual reality, artificial intelligence and online-mediated artworks. Schubert is a founding member of ensembles such as “Decoder“.


text
In the context of postdigitality, artistic practices can be understood as tools for making digital influences visible. This approach is based on the assumption that today the use of digital tools and forms of representation is no longer the exception but the rule, and that our interactions, ways of seeing, and images of the body are now significantly shaped by this circumstance. In particular, these approaches explore the question of whether, in this newly established condition, our view of the analog, non-digitally mediated environment has also changed. Post-digitality can be understood as a shift in perception. This readjustment of a viewpoint that is digitally influenced or reflective of the digital will be presented as a compositional strategy. This practice can be considered as a technique that actively thematizes the interpenetration of the analog by the digital and their interplay, thus making it possible to experience. The reconciliation of virtual and physical worlds and their artistic decoupling will be presented as a compositional approach and method of artistic research that attempts not only to convey these implications theoretically, but also to make them comprehensible to the senses.

**Comment by maccallum** [comment]
done
