### ISSUE TITLE
June 16 VR and 3D Sound

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#12]
Manifestations of Multimedia: VR and 3D Sound

June 16, 2021, 6:30pm UTC+2

 Lecture by Konstantina Orlandatou and Thomas Görne

Virtual Reality: Benefits, Constraints and Challenges of a New Artistic Medium 
 Konstantina Orlandatou

Virtual Reality (VR) has been a useful tool for many applications as well as designing experiences: from training simulations to immersive gaming experiences. 
Although VR already exists since the late 60s and technological advances make it more and more popular these days, still not everyone has an access to a headset or possesses one at home. We have some way to go before we can become the natives of this new medium. So what can we do with it in between? What are the benefits, constraints and challenges that this new medium brings along and how can we use this medium to create new artistic works? 
-----------------------------------------------------------------------------------------------------------------------------
CV:
Konstantina Orlandatou studied composition and music theory in Athens, Multimedia Composition (MA) at the University of Music and Drama in Hamburg and did her PhD in Systematic Musicology at the University of Hamburg (thesis with the working title "Synaesthetic and intermodal audio-visual perception: an experimental research"). As an active multimedia artist and musicologist she focuses on topics such as interactions between auditory and visual perception, visual mental imagery to music, synaesthesia and virtual reality. Currently she is leading the project "Moving Sound Pictures" in the University of Music and Drama in Hamburg, where she uses VR technologies to merge visual arts and music into one immersive interactive experience.
More information on the project you can find here: https://stage2.hfmt-hamburg.de/portfolio-item/moving-sound-pictures/
![KOrlandatou](https://user-images.githubusercontent.com/44872140/120445330-cb608100-c388-11eb-84b4-f2c5a5788cd6.jpg)

**Comment by dmuhr** [comment]
@fuxiao1208 is it possible to get CV info of Thomas Görne as well?

**Comment by fuxiao1208** [comment]
yes, here :)

Sound as things in space: Some thoughts on 3D Audio
by Thomas Görne

We imagine sound as things, as bounded and tangible physical objects in space. „3D“ is the way we perceive sound. And spatial language as a manifestation of spatial cognition is not just common in the description of spatial position and movement, but also in the description of pitch, timbre and intensity: A sound can be big or small, it can be edgy, sharp, flat or round, a tone can be high or low, a melody rising or falling. Can a listener distinguish between these metaphorical and physical properties of a sound? And how are spatial positions and trajectories of sound, spatial cognition and emotional impact related? The intedependencies between physical and metaphorical space become specifically interesting in „3D“ audio systems like VR audio, Ambisonics or multichannel sound, where position and movement in space become creative devices. 

==
Bio:
Thomas Görne was Professor of Theory of Music Transmission at Erich Thienhaus Institute (Tonmeister institute) of Hochschule für Musik Detmold 2004-2008. Since 2008 he is Professor of Audio Design and Audio Systems and head of the Sound Lab / Immersive Audio Lab at Hamburg University of Applied Sciences (HAW Hamburg). His main interests are virtual auditory spaces and the emotional impact of sound.  


![bunt_geschnitten_klein](https://user-images.githubusercontent.com/44872140/121500157-58858480-c9de-11eb-91fb-004c256bac83.jpg)

**Comment by fuxiao1208** [comment]
@dmuhr could you please add Thomas's lecture on Mutor website TODAY? I updated the information last Thursday. Thanks!

**Comment by dmuhr** [comment]
Hey, yes. I will.

**Comment by dmuhr** [comment]
done
