### ISSUE TITLE
Situated Instrument Design

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#13]
![rama_jan_21_](https://user-images.githubusercontent.com/44872140/122374981-1d95ca80-cf63-11eb-9ab8-0c4b5948d4f6.jpeg)

Situated Instrument Design

by Rama Gottfried (HfMT Hamburg)

In this talk I will give an overview on the history and theory of instrument design from a multimedia art practitioner perspective. Beginning with pre-historical developments, we will think into the human-object relationship and examine some of the social, political, and mystical implications of the incorporation of bodies and objects in performance practice, and discuss some of the key considerations that go into designing interactive instrument systems in different scales and contexts. In connection with these ideas, I will give a brief introduction to my use of computer vision in scenographic video-puppet-instrument performances.

Bio

Rama Gottfried’s recent works aim to increase our sensitivity to the web of relations that connect humans and the other animate and inanimate entities that surround us. Drawing on a variety of media and site-specific context, the pieces are conceived as voices and bodies; like microscopic seeds that fuse and scatter into the air, enveloping the room, and subtly expanding the audience’s attention to detail. 

Rama’s works have been featured at Lincoln Center's Mostly Mozart Festival, MaerzMusik, SPOR, Bludenzer Tage zeitgemäßer Musik, MATA, Klangwerkstatt, Rainy Days, and Ultima festivals, among others, and he has created sound installations for the Berliner Congress Center, Complice, Mino Washi Paper Museum, Stadtbad-Wedding, and Pacific Basin Building. In 2012, Rama was awarded the UC Berkeley George Ladd Composition Prize, and was selected for the musical-research residency at the Institut de Recherche et Coordination Acoustique/Musique (IRCAM) studying instrumental approaches to spatial audio technologies. In 2017, he was in residence at IRCAM and Zentrum für Kunst und Medientechnologie (ZKM) working on notation and audio/visual performance systems for spatial movement. In 2018, Rama joined the Hochschule für Musik und Theater Hamburg’s Department of Multimedia Composition as a Lecturer and Postdoctoral Researcher for the “Innovativ Hochschule: Stage_2.0 Alsterphilharmonie” project.

**Comment by fuxiao1208** [comment]
@dmuhr could you please put the infos on our website ASAP? I post it last Thursday, and think you would do it last Friday…

**Comment by dmuhr** [comment]
Done! Sorry I was working on one of the Units last friday and missed this issue.
