### ISSUE TITLE
Zoom Link for the Lectures  https://zoom.us/j/93844741848?pwd=QlJoQ3VucTVtQURjVklvL0FDQk1jdz09

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#2]
could you please put the link on the website?

Unless stated otherwise, the events will take place at https://zoom.us/j/93844741848?pwd=QlJoQ3VucTVtQURjVklvL0FDQk1jdz09

**Comment by maccallum** [comment]
done

**Comment by fuxiao1208** [comment]
all the events will take place at the same link, do you prefer to write it separate?

thanks :)

**Comment by maccallum** [comment]
Sorry, I'm not sure I understand? I put it in each of the event pages so that they can be shared individually, for example as direct links in a Facebook post or something. Did you have something else in mind?
