### ISSUE TITLE
Text and bios for Jacob's Presentation on April 28

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#4]
Sound Installation Art. Experiments in the borderlands of music and visual arts

April 28, 2021, 6:30pm 

Jacob Sello (HfMT)

Event link: https://zoom.us/j/93844741848?pwd=QlJoQ3VucTVtQURjVklvL0FDQk1jdz09
In the 20th century, working with sound is not the exclusive domain of musicians and composers. In Sound Installation Art the sonic elements turn out to be a space-consuming and sculptural material of the fine arts. In contrast to traditional music where time is the main concern, many sound artist focus on spacial aspects more than on time-based narrativity. Their “atmospheric soundscapes” often appear to be quasi-static, while the visitors are by no means passive consumers as in a classical concert hall: they move through the sonic environments at their individual pace and become interactive protagonists of their very own aesthetic experience. In sound installation art, the sounding atmospheres create moods and emotions constituting feelings and the subjective experience. In this introductory presentation historic and technological developments relevant for the emergence of interactive Sound Installations are discussed. In addition, dimensions of space and aesthetic are considered.

Bio 
Growing up as multi-instrumentalist, Jacob Sello (1976) played in various ensembles and bands of different musical styles. For 20 years he focuses on electronic music production, composition of interactive stage performances and sound installation art. He studied audio engineering (SAE Hamburg), multimedia composition (HfMT Hamburg, M.A.) and systematic musicology (Hamburg University) where he received a PhD for his research on the perception of sound art.   He loves exploring the vast potential of interactivity arising from the conjunction of trained musicians, traditional instruments and experimental sensor-technology – resulting in pieces for clarinet-driven RC-helicopters, realtime-generated instrumental scores extracted from dance gestures or music for a turntable-controlled pneumaticially prepared Disklavier. Jacob develops custom sensors and controllers for sound installations, modular synthesizers and interactive multimedia-performances. He is the creator of the award-winning Hexenkessel – a multitouch-enabled timpani, developed since 2010. His works have been internationally performed.  Currently, Jacob Sello is professor at HfMT Hamburg and director of HfMT´s Innovation Lab, where he creates novel interfaces for interdisciplinary stage arts. 

![jsello](https://user-images.githubusercontent.com/44872140/116064565-6da09100-a686-11eb-8657-8cfb5e49fc83.jpg)

**Comment by dmuhr** [comment]
done !
