### ISSUE TITLE
Audiovisual Performance A Lecture by Constantin Basic (CCRMA - Stanford University)

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#6]
Audiovisual Performance A Lecture by Constantin Basic (CCRMA - Stanford University)

Mai 5, 2021, 6:30pm UTC+2 / 9:30 GMT-7

HfMT Hamburg
Event link: https://zoom.us/j/93844741848?pwd=QlJoQ3VucTVtQURjVklvL0FDQk1jdz09

Please download his photo here https://drive.google.com/drive/folders/1BgUlSgmNvmfdYRgTHbqYET09enVHud0B

The unification of music and visual arts has been attempted throughout history, with opera being one instance. In the 20th Century, sounds and moving images have been syncretized in various art forms, such as film or video art, as well as in popular culture (television, music video, the Internet, etc.). Today, with rapid technological advancement and accessible hardware/software tools, artists employ both sonic and visual elements in their performance practice. What are the interrelations between music, video, and performers? Briefly touching on historical examples from the lineage of audiovisual genres, we will look at various theoretical frameworks and practices of engaging audiovisual media in the context of stage performance, with a focus on the scene of new music. Following the recent increase of works by composers who fuse video with music performance in similar ways, there is a need to delineate a new subgenre of multimedia, which will be proposed in this lecture.

/////////////////////
Constantin Basica is a Romanian composer living in the San Francisco Bay Area, whose current work focuses on symbiotic interrelations between music, video, and performers. His portfolio includes pieces for solo instruments, chamber ensembles, orchestra, electronics, and video, which have been performed in Europe, North America, and Asia at various venues, festivals, and conferences. Constantin earned a DMA in Composition at Stanford University under the guidance of Jaroslaw Kapuscinski, Brian Ferneyhough, Mark Applebaum, and Erik Ulman. His previous mentors were Georg Hajdu, Manfred Stahnke, Fredrik Schwenk, and Peter Michael Hamel during his MA and Erasmus Scholarship at the Hamburg University of Music and Drama (DE), as well as Dan Dediu and Bogdan Voda during his BA studies in Composition and Conducting at the National University of Music Bucharest (RO). As an educator, he has taught courses and conducted workshops at Stanford University, Escuela Superior de Música in Mexico City (MX), the 2016 SMC Summer School in Hamburg (DE), the International Center For Research And Education In Innovative Creative Technologies (CINETic) in Bucharest (RO), and the 2021 Network Performing Arts Production Workshops. Currently, Constantin is a postdoctoral scholar and the concert coordinator at Stanford’s Center for Computer Research in Music and Acoustics (CCRMA).<CCRMA high-resolution logo.png>

**Comment by maccallum** [comment]
done

**Comment by fuxiao1208** [comment]
@maccallum Could you please write the Titel:  Audiovisual Performance A Lecture by Constantin Basic (CCRMA - Stanford University) on the website, and the Time change to Mai 5, 2021, 6:30pm UTC+2 / 9:30 GMT-7 ? thanks!

**Comment by fuxiao1208** [comment]
Sorry, i made a mistake: his last name should be "Basica"
Audiovisual Performance A Lecture by Constantin Basica (CCRMA - Stanford University)
