### ISSUE TITLE
Cat Hope's lecture on Mai 19

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#8]
May 19, 2021, 6:30pm UTC+2

Cat Hope (Professor, Sir Zelman Cowen School of Music and Performance, Monash University)

Event link: https://zoom.us/j/93844741848?pwd=QlJoQ3VucTVtQURjVklvL0FDQk1jdz09

Cat Hope is a composer and musician. She is a classically trained flautist, self taught vocalist and experimental bassist who plays as a soloist and as part of other groups. Her compositions are conceptually driven, exploring the physicality of sound in different media, using graphic scores, acoustic /electronic combinations, aleatoric elements, drones, noise and glissandi. Her work has been discussed in books such as Sonic Writing (Magnusson, 2019), Loading the Silence (Kouvaris, 2013), Women of Note (Appleby, 2012), Sounding Postmodernism (Bennett, 2011) as well as periodicals such as Gramophone (UK, 2018), The Wire (UK, 2013), Limelight (Aus, 2012 - 2018) and Neu Zeitschrift Fur Musik Shaft (Germany, 2012, 2018). Her works have been recorded for Australian, German and Austrian national radio, as well as range of international labels.

Cat is the founder and artistic director of Decibel, a new music ensemble specialising in graphic notation and the combination of electronics and acoustic instruments. This group has released over 4 albums, and developed an innovated application for reading graphic notation in chamber music settings. She has also founded pop groups – singing and playing bass (Gata Negra (1997-2004), noise bands as a bassist (Abe Sada (2004-2014), Lux Mammoth (1996-2003)) and audio-visual groups (CavITY, 200-2004). She has played in bands as a bass and flute player – primarily in Europe with Hugo Race, Cesare Basile, Tim Evans and Marta Collica, and has been invited to international festivals such as MEM Spain and ISEA. She has toured the US, Europe and Japan multiple times as a bass soloist, in bands and as a support for acts such as Acid Mother Temple, Whitehouse, Lee Rinaldo, Nirvana, Hole and others. She collaborates regularly with musicians and composers such as KK Null (Japan), Lionel Marchetti and Eliane Radigue (France) as well as visual artists such as Erin Coates (Aus), Kate McMillan (UK) and Tracey Moffat (Australia).

Hope worked closely with Tura new music during her time in WA, supporting festival and concert programming as well as developing partnerships with Tura and the academy for PhD scholarships and touring artists. She has sat on boards such as PICA, the Australian Music Centre, the New Music Network and has been a peer assessor on state and commonwealth grant panels, APRA professional development, Myer Composition awards and APRA AMC awards to name a few. As well as being a composer and performer, she has developed a range of sound installations, film music and has curated visual art exhibitions around graphic notation. He work has been shown in art galleries and concert halls alike.

www.cathope.com

![CatHope_HLohr_sml](https://user-images.githubusercontent.com/44872140/118474378-48de8d00-b70b-11eb-97ad-6c3edad1a4d1.jpeg)

**Comment by maccallum** [comment]
Is there a summary or abstract for this talk, @fuxiao1208 ?

**Comment by fuxiao1208** [comment]
unfortunately not, cat is in hospital, her partner will send us a pre-recording video today..., thanks John

**Comment by maccallum** [comment]
ok, I'll leave it blank then. reopen this if there is anything to add
