### ISSUE TITLE
Johannes Kreidler

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/HistoryAndPracticeOfMultimedia#9]
Manifestations of Multi Media Music: New Conceptualism

May 26, 2021, 6:30pm UTC +2
A Lecture by Johannes Kreidler (Hochschule für Musik Basel)

Event link: https://zoom.us/j/93844741848?pwd=QlJoQ3VucTVtQURjVklvL0FDQk1jdz09

Concept-art was established in the 1960s as a practice and label. It is "idea art" - central to it are mental concepts, framings, which can be realised in various ways. (And thus the essence of framing itself always becomes a topic.) Think of the open form of Marcel Duchamp's readymade, the infinite possibilities of performing John Cage's silent piece 4:33, etc., all the way to today's meme culture on the internet.
Despite the media-nonspecificity that mental concepts first have, and the multi-mediality in which they are then implemented, conceptual art first became paradigmatic in the visual arts, while in music (as well as in theater and literature) only found its way extensively in the new millennium – the “new conceptualism”. The latter is due to the added possibilities of the digital. 
But if the conceptual now encompasses all the arts, everything actually becomes multimedia art. The question then arises as to what specifically still constitutes >music< or what can constitute it in the future. Conceptual thinking in the arts has posed and continues to pose exciting challenges.

///////////////////////

Johannes Kreidler (1980) studied composition, electronic music and music theory in Freiburg and The Hague, among others with mathias spahlinger and Orm Finnendahl. In 2012 he was awarded the Kranichsteiner Music Prize of the Darmstadt Summer Course for New Music. Since 2019, he is Professor for Composition at the Hochschule für Musik Basel.

Performances (selection): Donaueschinger Musiktage, Wittener Tage für Neue Kammermusik, Ultraschall Berlin, MaerzMusik Berlin, Foreign Affairs Berlin, Volksbühne am Rosa-Luxemburg-Platz Berlin, Elbphilharmonie Hamburg, Eclat Stuttgart, Biennale Venice, Gaudeamus Music Week Amsterdam, Warsaw Autumn, Biennale de Musique en Scène Lyon, Ultima Festival Oslo, Huddersfield Contemporary Music Festival, Musica Strasbourg, MusicAcoustica Festival Beijing, Liquid Architecture Melbourne

Wolke-Verlag published the books Loadbang. Programming Electronic Music in Puredata (2009), Musik mit Musik – Texte 2005-2011 (2012) and Sätze über musikalische Konzeptkunst. Texte 2012-2018 (2018).

[www.kreidler-net.de]

![01kreidler--by-Esther Kochte-kleiner](https://user-images.githubusercontent.com/44872140/118481008-4bdd7b80-b713-11eb-8f66-95b4c22831c1.jpg)

**Comment by fuxiao1208** [comment]
copyright: Foto: Esther Kochte

**Comment by fuxiao1208** [comment]
Could you please write the copyright on the website? Thanks! Foto: Esther Kochte 
And please for each Presentation only one time: 6:30pm UTC+2 

Thanks! @maccallum

**Comment by maccallum** [comment]
done
